[2025-05-20 14:47:14,469] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: ETLWeatherPostgres.load manual__2025-05-20T14:47:10.707102+00:00 [queued]>
[2025-05-20 14:47:14,476] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: ETLWeatherPostgres.load manual__2025-05-20T14:47:10.707102+00:00 [queued]>
[2025-05-20 14:47:14,476] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2025-05-20 14:47:14,476] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2025-05-20 14:47:14,477] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2025-05-20 14:47:14,485] {taskinstance.py:1264} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2025-05-20 14:47:10.707102+00:00
[2025-05-20 14:47:14,490] {standard_task_runner.py:52} INFO - Started process 1921 to run task
[2025-05-20 14:47:14,492] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ETLWeatherPostgres', 'load', 'manual__2025-05-20T14:47:10.707102+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/02-ETLWeatherPostgres.py', '--cfg-path', '/tmp/tmp3u_1n6za', '--error-file', '/tmp/tmpuz753l5g']
[2025-05-20 14:47:14,493] {standard_task_runner.py:77} INFO - Job 57: Subtask load
[2025-05-20 14:47:14,537] {logging_mixin.py:109} INFO - Running <TaskInstance: ETLWeatherPostgres.load manual__2025-05-20T14:47:10.707102+00:00 [running]> on host fabc4724d39b
[2025-05-20 14:47:14,585] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETLWeatherPostgres
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2025-05-20T14:47:10.707102+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-20T14:47:10.707102+00:00
[2025-05-20 14:47:14,590] {logging_mixin.py:109} INFO - 1 Record inserted successfully into table
[2025-05-20 14:47:14,591] {logging_mixin.py:109} INFO - PostgreSQL connection is closed
[2025-05-20 14:47:14,591] {python.py:175} INFO - Done. Returned value was: None
[2025-05-20 14:47:14,600] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=ETLWeatherPostgres, task_id=load, execution_date=20250520T144710, start_date=20250520T144714, end_date=20250520T144714
[2025-05-20 14:47:14,624] {local_task_job.py:154} INFO - Task exited with return code 0
[2025-05-20 14:47:14,647] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
